# Generated by Django 3.1.5 on 2021-02-01 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_reserve_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreservation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserved_books', to='book.book'),
        ),
    ]
