# Generated by Django 3.1.5 on 2021-02-02 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20210201_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreservation',
            name='delivery_date',
        ),
    ]
