version: '3'

services:
  db:
    image: postgres:10.12-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-book_store}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
  app:
    build:
      context: .
    #entrypoint: ./docker/entrypoint.web.sh
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-book_store}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
    ports:
      - "8000:8000"
    depends_on:
      - db