version: '3'

services:
  db:
    image: postgres:10.12-alpine
    container_name: db
    ports:
      - "6543:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=book_store"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  app:
    build: .
    volumes:
      - .:/app/
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data: